0x05:
  sensorType: 0x0F
  path: /xyz/openbmc_project/state/host0
  sensorReadingType: 0x6F
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: eventdata2
  interfaces:
    xyz.openbmc_project.State.Boot.Progress:
      BootProgress:
        Offsets:
          0x13:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.OSStart
          0x00:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.Unspecified
          0x01:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.MemoryInit
          0x07:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.PCIInit
          0x14:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.MotherboardInit
          0x03:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.SecondaryProcInit
0x08:
  sensorType: 0x07
  path: /org/open_power/control/occ_3_0050
  sensorReadingType: 0x09
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: assertion
  interfaces:
    org.open_power.OCC.Status:
      OccActive:
        Offsets:
          0x00:
            assert: false
            deassert: true
            type: bool
          0x01:
            assert: true
            deassert: false
            type: bool
0x09:
  sensorType: 0xC3
  path: /xyz/openbmc_project/state/host0
  sensorReadingType: 0x6F
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingAssertion
  interfaces:
    xyz.openbmc_project.Control.Boot.RebootAttempts:
      AttemptsLeft:
        Offsets:
          0xFF:
            type: uint32_t
0x1e:
  sensorType: 0x0C
  path: /system/chassis/motherboard/dimm0
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x06:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x04:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x06:
            assert: true
            deassert: false
            type: bool
0x1f:
  sensorType: 0x0C
  path: /system/chassis/motherboard/dimm1
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x06:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x04:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x06:
            assert: true
            deassert: false
            type: bool
0x20:
  sensorType: 0x0C
  path: /system/chassis/motherboard/dimm2
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x06:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x04:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x06:
            assert: true
            deassert: false
            type: bool
0x21:
  sensorType: 0x0C
  path: /system/chassis/motherboard/dimm3
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x06:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x04:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x06:
            assert: true
            deassert: false
            type: bool
0x22:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core0
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x23:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core1
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x24:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core2
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x25:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core3
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x26:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core4
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x27:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core5
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x28:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core6
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x29:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core7
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x2a:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core8
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x2b:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core9
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x2c:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core10
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x2d:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0/core11
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
            skipOn: deassert
0x2f:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
0x32:
  sensorType: 0x1F
  path: /xyz/openbmc_project/state/host0
  sensorReadingType: 0x6F
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: assertion
  interfaces:
    xyz.openbmc_project.State.OperatingSystem.Status:
      OperatingSystemState:
        Offsets:
          0x02:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.PXEBoot
            type: string
          0x06:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.BootComplete
            type: string
          0x04:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.CDROMBoot
            type: string
          0x01:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.CBoot
            type: string
          0x03:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.DiagBoot
            type: string
          0x05:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.ROMBoot
            type: string
