- name: fan0
  path: /system/chassis/motherboard/fan0
  methods:
    - type: gpio
      key: 5
      physpath: /sys/devices/platform/ahb/ahb:apb/ahb:apb:bus@1e78a000/1e78a100.i2c/i2c-3/3-0060
      devpath: /dev/input/by-path/platform-gpio-keys-polled-event
    - type: tach
      sensors:
        - fan0_0
  rpolicy:
    type: anyof

- name: fan1
  path: /system/chassis/motherboard/fan1
  methods:
    - type: gpio
      key: 6
      physpath: /sys/devices/platform/ahb/ahb:apb/ahb:apb:bus@1e78a000/1e78a100.i2c/i2c-3/3-0060
      devpath: /dev/input/by-path/platform-gpio-keys-polled-event
    - type: tach
      sensors:
        - fan1_0
  rpolicy:
    type: anyof

- name: fan2
  path: /system/chassis/motherboard/fan2
  methods:
    - type: gpio
      key: 7
      physpath: /sys/devices/platform/ahb/ahb:apb/ahb:apb:bus@1e78a000/1e78a100.i2c/i2c-3/3-0060
      devpath: /dev/input/by-path/platform-gpio-keys-polled-event
    - type: tach
      sensors:
        - fan2_0
  rpolicy:
    type: anyof

- name: fan3
  path: /system/chassis/motherboard/fan3
  methods:
    - type: gpio
      key: 8
      physpath: /sys/devices/platform/ahb/ahb:apb/ahb:apb:bus@1e78a000/1e78a100.i2c/i2c-3/3-0060
      devpath: /dev/input/by-path/platform-gpio-keys-polled-event
    - type: tach
      sensors:
        - fan3_0
  rpolicy:
    type: anyof

# Boost fan presence
- name: fan4
  path: /system/chassis/motherboard/fan4
  methods:
    - type: gpio
      key: 9
      physpath: /sys/devices/platform/ahb/ahb:apb/ahb:apb:bus@1e78a000/1e78a100.i2c/i2c-3/3-0060
      devpath: /dev/input/by-path/platform-gpio-keys-polled-event
  rpolicy:
    type: anyof
